# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5000)),
                ('color', models.CharField(max_length=5000)),
                ('favoritefood', models.CharField(max_length=5000)),
                ('favoritetoy', models.CharField(max_length=5000)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Plant')),
            ],
        ),
        migrations.RenameModel(
            old_name='Breed',
            new_name='Species',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
