# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-12 19:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211112_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='favoritefood',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='favoritetoy',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='species',
            name='exerciseneeds',
        ),
        migrations.RemoveField(
            model_name='species',
            name='friendliness',
        ),
        migrations.RemoveField(
            model_name='species',
            name='sheddingamount',
        ),
        migrations.RemoveField(
            model_name='species',
            name='trainability',
        ),
        migrations.AddField(
            model_name='species',
            name='Harvest_age',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='species',
            name='Humidity',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='species',
            name='nutrient_amount',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='species',
            name='tempurature',
            field=models.IntegerField(default='33', validators=[django.core.validators.MinValueValidator(33), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='species',
            name='water_requirement',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
