# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211112_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('age', models.IntegerField()),
                ('experience', models.CharField(max_length=5000)),
                ('level', models.CharField(choices=[('Serious Players Only', 'Serious Players Only'), ('Play Hard, not Hurt', 'Play Hard, not Hurt'), ('Just Having Fun', 'Just Having Fun')], max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
