# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-05 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211205_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='api.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='api.Profile'),
        ),
    ]
