# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20211205_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('age', models.IntegerField()),
                ('experience', models.CharField(max_length=5000)),
                ('level', models.CharField(choices=[('Serious Players Only', 'Serious Players Only'), ('Play Hard, not Hurt', 'Play Hard, not Hurt'), ('Just Having Fun', 'Just Having Fun')], max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
