# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
