# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211206_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(to='api.PlayerProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(to='api.PlayerProfile'),
        ),
    ]
