# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211206_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'ordering': ['id']},
        ),
    ]
