# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211208_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Name', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
