# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-14 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211212_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.CharField(choices=[('Serious Players Only', 'Serious Players Only'), ('Play Hard, not Hurt', 'Play Hard, not Hurt'), ('Just Having Fun', 'Just Having Fun')], default='Just Having Fun', max_length=5000),
        ),
    ]
